Atualização do Front-end do projeto
CaesarCrew/Eng_Soft-Grupo1 pull request #42
Opened 2024-05-31 23:26 UTC by CaesarCrew

2024-06-02 12:14 UTC, gabrielbdsm requested changes
**Login da Secretaria:**

O formulário de login não possui um botão de submit, tornando impossível enviar os dados.
O layout está desalinhado, dificultando a usabilidade e a compreensão.
A responsividade está péssima, o que torna a página difícil de usar em dispositivos móveis.
O título correto da página deve ser "Login Secretaria".

**Login de Usuário:**

O título da página está incorreto e deve ser ajustado para refletir corretamente a função da página.
A responsividade da página é péssima, tornando-a inadequada para dispositivos móveis.

**Cadastro de Usuário:**

A página está totalmente desalinhada e desorganizada, comprometendo a experiência do usuário.
A responsividade é péssima, dificultando o uso em dispositivos móveis.
O link de redirecionamento está incorreto, direcionando para a página errada.

**Horários da Secretaria:**

A página não é responsiva, prejudicando a usabilidade em diferentes dispositivos.
Há falta de alinhamento nos elementos da página, afetando a estética e a clareza das informações.

2024-06-02 12:15 UTC, gabrielbdsm requested changes
página home também deve ser alinhada

2024-06-02 12:29 UTC, gabrielbdsm requested changes
outro detalhe , não se deve agrupar todo css em um arquivo , pois dificulta manutenção futuras e com a evolução do projeto pode ocorre conflitos entre classes e id. estou manda um esboço como exemplo

my_project/
├── app/
│   ├── Controllers/
│   │   └── HomeController.php
│   ├── Models/
│   │   └── UserModel.php
│   ├── Views/
│   │   ├── home/
│   │   │   └── index.php
│   │   └── layout/
│   │       └── header.php
│   └── Helpers/
│       └── utils.php
├── config/
│   ├── database.php
│   └── app.php
├── public/
│   ├── css/
│   │   └── styles.css
           └──login.css
│   ├── js/
│   │   └── scripts.js
│   └── index.php
├── routes/
│   └── web.php
├── storage/
│   ├── logs/
│   │   └── app.log
│   └── cache/
├── tests/
│   └── Feature/
│       └── ExampleTest.php
├── vendor/
│   └── autoload.php
├── .env
├── .gitignore
├── composer.json
└── README.md

2024-06-04 00:31 UTC, gabrielbdsm requested changes
https://github.com/Kal-il/ES-2023_2-Adoteme/tree/main/src/view 
Login user front não faz sentido ter o html dos login e o style segue junto , mandei outro exemplo de como deve ser seguido

2024-06-05 02:51 UTC, gabrielbdsm requested changes
ao utilizar sua branch o sistema quebra 
https://youtu.be/-4kBAtuQ21M

2024-06-05 11:13 UTC, CaesarCrew commented
> ao utilizar sua branch o sistema quebra https://youtu.be/-4kBAtuQ21M

No meu tava funcionando normal

2024-06-19 01:58 UTC, closed without merging